### ISSUE TITLE
Following documentation fails for xamarin android.

### ISSUE THREAD

**Issue by christophedemey** [Anyline/anyline-ocr-xamarin-module#5]
Hi 

I am trying to use the sdk but come acros some problems.

Documentation Url : https://documentation.anyline.com/toc/platforms/xamarin/xamarin.android/xamarin.android_implementation.html
Section : Adding a scan view.

When i put in the xml shown i do not get the resulting image.
I get a view with following error message : 

![scanviewerror](https://user-images.githubusercontent.com/13153164/45930720-e20d7380-bf63-11e8-8e36-f30e76281828.png)

Ignoring this, continuing the tutorial until the end, i then try to launch (debug) the app and i get following exception : 

![exception](https://user-images.githubusercontent.com/13153164/45930903-171ac580-bf66-11e8-89cf-52fa83dd1db6.JPG)

I have pushed this code into a public repository for you to check : https://github.com/christophedemey/anylineocrtest

The dll reference to the sdk is also in the root of this repository.
This will probably make it allot easier for you to find the problem.
Hope to hear from you guys soon, thanks.

**Comment by peterAnyline** [comment]
Hello Christoph,

you can usually ignore the NoClassDefFoundError in the designer. This is just a rendering issue because the AXML designer can't compile the scan view at this point.

As for the UnsatisfiedLinkError: Please try to untick the x64 architectures in your project settings:

![grafik](https://user-images.githubusercontent.com/15013485/45932753-a08bc100-bf81-11e8-8712-d8202884848d.png)

Do you still have issues launching the app?

Best regards,
Peter

**Comment by christophedemey** [comment]
Hi

This was the problem, thanks, please considder adding this to the documentation as it is not something obvious.

Thanks!
