### ISSUE TITLE
Anyline Energy reader problem

### ISSUE THREAD

**Issue by christophedemey** [Anyline/anyline-ocr-xamarin-module#7]
Hi

After successfully addin the scanview in a native android application i have now implemented the energy reader page in xamarin forms through your example with a custom page render.
The problem i have is that the ocr reader is unable to detect the number 1 on my meter.
Please review attached screenshot, i have ofcourse tried multiple times.
Maybe i need some other configuration or training files ?
![screenshot_20180928-111705](https://user-images.githubusercontent.com/13153164/46199987-b813d280-c310-11e8-83eb-0dca7301e7e5.jpg)

Thanks

**Comment by peterAnyline** [comment]
Dear christoph,

I've talked to my colleagues about this - it seems that our neural network filters that "1", probably because it looks like the black space between digits - we're going to investigate this further and will get back to you. If you have any other images of meters that you have trouble scanning with, could you send them to us?

Best regards
Peter

**Comment by christophedemey** [comment]
Hi @peterAnyline 

So the meter incremented the 1 and i tried again with even more unwanted results, i have collected some screenshot for you but this does not seem to work at all with this font/style.

Please let me know if you have any news for me.

![screenshot_20181006-215809_anyline ocr](https://user-images.githubusercontent.com/13153164/46575355-3bd65a80-c9b4-11e8-8c2e-8c0228ee255c.jpg)
![20181006_215710](https://user-images.githubusercontent.com/13153164/46575356-3bd65a80-c9b4-11e8-8cd1-9fdb47a2a141.jpg)
![20181006_215707](https://user-images.githubusercontent.com/13153164/46575357-3bd65a80-c9b4-11e8-987a-1e585fda43c0.jpg)
![20181006_215700](https://user-images.githubusercontent.com/13153164/46575358-3bd65a80-c9b4-11e8-9a04-6d480d70c6a5.jpg)
![20181006_215658](https://user-images.githubusercontent.com/13153164/46575359-3c6ef100-c9b4-11e8-8a59-2bc9bc6024d5.jpg)
![screenshot_20181006-215830_anyline ocr](https://user-images.githubusercontent.com/13153164/46575360-3c6ef100-c9b4-11e8-9dc4-cf57b43f489f.jpg)
![screenshot_20181006-215858_anyline ocr](https://user-images.githubusercontent.com/13153164/46575361-3c6ef100-c9b4-11e8-97f3-7a81965a4f8b.jpg)

**Comment by peterAnyline** [comment]
Thank you for the images! We will have a look and get back to you as soon as we have any info updates!

**Comment by christophedemey** [comment]
Hi @peterAnyline 
FYI:
I have checked the picture against the microsoft vision api and it filters out the text just fine.

![microsoftcogn](https://user-images.githubusercontent.com/13153164/46575413-de8ed900-c9b4-11e8-9b03-a60a55949ce4.JPG)

**Comment by christophedemey** [comment]
Hi @peterAnyline 

How are things going ?
I am eager to start using this, sorry for bothering you so much ^^

**Comment by peterAnyline** [comment]
Hi! Sorry for the delayed reply!
I'm aware that Microsoft might perform better OCR in this case. Our Meter reading (Energy) module specializes on specific types of meters in the D/A/CH region at the moment and is not (yet) trained for the meter type(s) that you showed us. As this is an issue with our product and not actually the Xamarin wrapper, please contact us at support@anyline.com so that we can find a solution!
